### ISSUE TITLE
Upgrade without ask at each packages

### ISSUE THREAD

**Issue by sebtiz13** [th0r/npm-upgrade#48] opened 2020-06-18 14:00 UTC
Hello thank for your great package

But it's possible to upgrade without ask if i want upgrade on each packages ?
like `npm-upgrade -y` for "yes for all"

**Comment by th0r** [comment] 2020-06-18 14:02
Maybe https://github.com/raineorshine/npm-check-updates is what you need?

**Comment by th0r** [comment] 2020-06-19 06:53
@sebtiz13?

**Comment by sebtiz13** [comment] 2020-06-19 08:38
Yes it's an feature like 

`ncu -u`

what i talking about

**Comment by th0r** [comment] 2020-06-19 10:31
But why don't use `ncu` then?

**Comment by th0r** [comment] 2020-06-19 10:35
But why don't use `ncu` then? Anyway, it's a duplicate of https://github.com/th0r/npm-upgrade/issues/3 - you can find all the reasons there.

**Closed by th0r** 2020-06-19 10:35 UTC

**Comment by sebtiz13** [comment] 2020-06-19 13:59
sorry i didn't know ncu but your reasons in #3 are good and indeed it's better to check all package updated in some many case, but in my case was for automation. So I have note for ncu.

Thanks for the discovery and sorry for duplicate.
