### ISSUE TITLE
-yes argv for auto yes

### ISSUE THREAD

**Issue by bluelovers** [th0r/npm-upgrade#19] opened 2018-02-13 03:53 UTC
can we have "--yes" argv for auto choose yes
and a "--install" agrv for auto run npm install after

**Comment by th0r** [comment] 2018-02-13 04:39
Auto choose "yes" for what questions?

**Comment by bluelovers** [comment] 2018-02-13 08:51
something like use npm run script

**Comment by th0r** [comment] 2018-02-13 13:01
Duplicate of https://github.com/th0r/npm-upgrade/issues/3

**Closed by th0r** 2018-02-13 13:01 UTC
